using JetBrains.Annotations;

using Reaganism.FBI.Textual.Fuzzy.Patching;

namespace Reaganism.CDC.Patching;

/// <summary>
///     Settings for file patching.
/// </summary>
[PublicAPI]
public class PatcherSettings(string originalDirectory, string modifiedDirectory, string patchesDirectory, Patcher.Mode mode = Patcher.Mode.Fuzzy)
{
    /// <summary>
    ///     The path to the original, unmodified files.
    /// </summary>
    [PublicAPI]
    public string OriginalDirectory { [PublicAPI] get; } = originalDirectory;

    /// <summary>
    ///     The path to the new, modified files.
    /// </summary>
    [PublicAPI]
    public string ModifiedDirectory { [PublicAPI] get; } = modifiedDirectory;

    /// <summary>
    ///     The path to the directory that contains diffed patches generated by
    ///     comparing the modified directory to the original directory.
    /// </summary>
    [PublicAPI]
    public string PatchesDirectory { [PublicAPI] get; } = patchesDirectory;

    /// <summary>
    ///     The mode to use when patching files.
    /// </summary>
    [PublicAPI]
    public Patcher.Mode Mode { [PublicAPI] get; } = mode;
}